# Generated by Django 3.2.12 on 2022-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=256)),
            ],
        ),
    ]
