# Generated by Django 3.2.12 on 2022-12-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddyget', '0002_budgetrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrow',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='buddyget.budget'),
        ),
    ]
